"""Words that name a kind of thing rather than a particular product.

This lives in core/ because two packages that may not import each other both
need it. ledger/ uses it to decide whether a phrase the user wrote pins a
product at all; policy/ uses it to decide whether the product that arrived
answers the one that was pinned. Keeping two copies would let them drift, and a
drift here shows up as a payment wrongly refused.

It is data, not logic: no decision is taken in this module.
"""

from __future__ import annotations

# Words that describe any product, or how one is packaged and sold.
GENERIC_PRODUCT_WORDS = frozenset(
    {
        "a",
        "an",
        "the",
        "of",
        "for",
        "pair",
        "set",
        "new",
        "some",
        "any",
        "item",
        "items",
        "product",
        "products",
        "thing",
        "things",
        "one",
        "unit",
        "units",
        "running",
        "wireless",
        "electric",
        "plain",
        "small",
        "medium",
        "large",
        "cheap",
        "good",
        "best",
    }
)


# Words that name the kind of thing a category contains. A reference made only
# of these names no particular product: "running shoes" is a kind, "Asics
# Gel-Contend 9" is a product.
CATEGORY_WORDS: dict[str, tuple[str, ...]] = {
    "footwear": (
        "shoe",
        "shoes",
        "sneaker",
        "sneakers",
        "boot",
        "boots",
        "sandal",
        "sandals",
        "trainers",
        "heels",
        "slippers",
    ),
    "electronics": (
        "laptop",
        "phone",
        "headphone",
        "headphones",
        "earphone",
        "earphones",
        "camera",
        "monitor",
        "speaker",
        "tablet",
        "charger",
        "keyboard",
        "mouse",
        "smartwatch",
        "television",
        "tv",
        "printer",
        "router",
    ),
    "apparel": (
        "shirt",
        "shirts",
        "tshirt",
        "t-shirt",
        "jacket",
        "jeans",
        "dress",
        "kurta",
        "saree",
        "socks",
        "trousers",
        "sweater",
    ),
    "home_kitchen": (
        "kettle",
        "blender",
        "lamp",
        "chair",
        "table",
        "mattress",
        "sofa",
        "refrigerator",
        "fridge",
        "cooker",
        "purifier",
        "towel",
        "clock",
        "fan",
        "grinder",
        "mug",
        "pillow",
        "organiser",
        "organizer",
    ),
    "books": (
        "book",
        "books",
        "novel",
        "paperback",
        "textbook",
        "notebook",
        "notebooks",
        "paper",
        "ream",
        "reams",
    ),
    "grocery": (
        "grocery",
        "groceries",
        "protein",
        "coffee",
        "tea",
        "rice",
        "snack",
        "lunch",
        "dinner",
    ),
    "beauty": (
        "serum",
        "perfume",
        "soap",
        "shampoo",
        "moisturiser",
        "moisturizer",
        "lipstick",
        "sunscreen",
    ),
    "sports": (
        "bat",
        "racquet",
        "racket",
        "yoga",
        "treadmill",
        "dumbbell",
        "helmet",
        "bicycle",
        "bottle",
        "pump",
        "cricket",
    ),
    "toys": ("toy", "toys", "puzzle", "lego", "chess", "board game"),
    "accessories": (
        "bag",
        "backpack",
        "wallet",
        "belt",
        "watch strap",
        "suitcase",
        "phone case",
        "case",
    ),
}
