"""Orchestration: run the engine, time it, record it, answer.

Timing lives here and deliberately not in policy/. Measuring elapsed time means
reading a clock, and a clock inside the engine makes the engine's output depend
on when it ran. Keeping the stopwatch outside preserves both properties at once:
the decision is reproducible, and it is still observable.
"""

from __future__ import annotations

import time
import uuid
from datetime import datetime

from ..audit.records import AuditRecord, ComplianceReceipt
from ..audit.store import AuditLog
from ..core.decision import Decision, LatencyBreakdown
from ..core.enums import Outcome
from ..core.hashing import content_hash, offer_hash
from ..core.intent import IntentLedger
from ..core.offer import Offer
from ..policy import CHECKS_PERFORMED, evaluate

_MS = 1000.0


def escalation_question(decision: Outcome, violations) -> str | None:
    """Assembled from the violations, not generated by a model.

    An escalation asks the user to make a call the system could not make. The
    words in front of them are the explanations the engine already produced, so
    the question cannot say anything the deterministic checks did not find.
    """
    if decision is not Outcome.ESCALATE:
        return None
    reasons = [v.explanation for v in violations if v.outcome is Outcome.ESCALATE]
    if not reasons:
        return None
    body = " ".join(reasons)
    return f"{body} Do you want to go ahead with this order?"


def run_gate(
    ledger: IntentLedger,
    offer: Offer,
    *,
    now: datetime,
    log: AuditLog | None = None,
    human_confirmed: bool = False,
) -> tuple[Decision, AuditRecord]:
    """Decide, time, record. The audit record is written before anything else acts."""
    started = time.perf_counter()

    arithmetic_started = time.perf_counter()
    result = evaluate(ledger, offer, now=now)
    arithmetic_ms = (time.perf_counter() - arithmetic_started) * _MS

    latency = LatencyBreakdown(
        arithmetic_ms=arithmetic_ms,
        total_ms=(time.perf_counter() - started) * _MS,
    )

    decision = Decision(
        decision=result.outcome,
        intent_id=ledger.intent_id,
        offer_id=offer.offer_id,
        violations=result.violations,
        escalation_question=escalation_question(result.outcome, result.violations),
        latency_ms=latency,
        checked_at=now,
    )

    record = AuditRecord(
        record_id=f"aud_{uuid.uuid4().hex[:12]}",
        sequence=0,
        previous_hash="",
        intent_id=ledger.intent_id,
        offer_id=offer.offer_id,
        mandate_hash=content_hash(ledger),
        offer_hash=offer_hash(offer),
        decision=result.outcome,
        violations=result.violations,
        checked_total_paise=result.checked_total_paise,
        max_total_paise=ledger.hard.max_total_paise,
        latency_ms=latency,
        human_confirmed=human_confirmed,
        checked_at=now,
    )
    if log is not None:
        record = log.append(record)
    return decision, record


def issue_receipt(record: AuditRecord) -> ComplianceReceipt:
    """The merchant's dispute evidence. Only an ALLOW earns one."""
    if record.decision is not Outcome.ALLOW:
        raise ValueError(
            f"a receipt attests that money was authorized; this decision was "
            f"{record.decision.value}"
        )
    return ComplianceReceipt(
        receipt_id=f"rcp_{uuid.uuid4().hex[:12]}",
        intent_id=record.intent_id,
        offer_id=record.offer_id,
        mandate_hash=record.mandate_hash,
        offer_hash=record.offer_hash,
        decision=record.decision,
        constraints_checked=CHECKS_PERFORMED,
        amount_authorized_paise=record.checked_total_paise,
        human_confirmed=record.human_confirmed,
        issued_at=record.checked_at,
    )
